### ISSUE TITLE
The switches peripheral does not work

### ISSUE THREAD

**Issue by aenrbes** [litex-hub/linux-on-litex-vexriscv#117]
switch is an input device, but a GPIOOut is used [here:](https://github.com/litex-hub/linux-on-litex-vexriscv/blob/master/soc_linux.py#L130):
def add_switches(self):
            self.submodules.switches = GPIOOut(Cat(platform_request_all(self.platform, "user_sw")))
            self.add_csr("switches")

**Comment by enjoy-digital** [comment]
Thanks for catching this. I introduced this while refactoring the `add_switches` method after merging. This is fixed with https://github.com/litex-hub/linux-on-litex-vexriscv/commit/0da02faf9a01b312461862d9579a208ceee7dcd6. Sorry for the inconvenience.
