### ISSUE TITLE
why emulator ignores '\r'?

### ISSUE THREAD

**Issue by frantony** [litex-hub/linux-on-litex-vexriscv#124]
@enjoy-digital 

At the moment the ``litex_putchar()`` function ignores the carriage return character ``\r``.
As a result the linux bootlog via sbi console is distorted.

Here is minicom with enabled linewrapping screenshot:

![litex-emulator-no-cr](https://user-images.githubusercontent.com/416815/78361453-19c99280-75c1-11ea-8257-145512434743.png)

This change fixes the problem:
```
--- a/emulator/main.c
+++ b/emulator/main.c
@@ -39,7 +39,7 @@ static void litex_putchar(char c){
     full = 1;
     while ((full & 0x1) != 0)
         full = uart_txfull_read();
-    if (c != '\r')
+//    if (c != '\r')
         uart_rxtx_write(c);
 }

```

**Comment by enjoy-digital** [comment]
@frantony sorry for the delay, I don't remember the exact  reason for this, but this is not present in OpenSBI port (https://github.com/litex-hub/opensbi/blob/0.8-linux-on-litex-vexriscv/platform/litex/vexriscv/litex.c#L55-L59) that will be used with #165.

**Comment by enjoy-digital** [comment]
https://github.com/litex-hub/linux-on-litex-vexriscv/pull/165 has been merged, we can now close this.
