### ISSUE TITLE
Integrate LiteEth

### ISSUE THREAD

**Issue by enjoy-digital** [litex-hub/linux-on-litex-vexriscv#13]
- [x] 1) Regenerate VexRiscv to have similar interrupts for User/Supervisor mode.
- [x] 2) Get actual LiteEth Linux driver working (in polling mode).
- [x] 3) Add interrupt support to software.
- [x] 4) Review driver, do eventual optimizations, understand limitations.
- [ ] 5) Add DMA support if needed to improve performance.

**Comment by Dolu1990** [comment]
Hi,

How things are going on it ? What is blocking ?
Regenerate VexRiscv to have similar interrupts for User/Supervisor mode can be checked right ?

**Comment by enjoy-digital** [comment]
Hi @Dolu1990,

yes sorry, nothing blocking, just that i haven't spent time on it :)

**Comment by Dolu1990** [comment]
No worries, i'm just asking to be sure there is nothing dramatic happening ^^

**Comment by frantony** [comment]
Please see https://github.com/enjoy-digital/linux-on-litex-vexriscv/pull/18

**Comment by enjoy-digital** [comment]
@frantony i just regenerated everything from upstream and tested successfully ethernet in polling mode, thakns.

**Comment by enjoy-digital** [comment]
LiteEth is now working with decent performance. We could add a DMA in the future but we can consider the integration done.
