### ISSUE TITLE
Update Image Load Command

### ISSUE THREAD

**Issue by mescoba1** [litex-hub/linux-on-litex-vexriscv#148]
Looks like `images.json` has been changed to `buildroot/boot.json`, perhaps README should be updated to reflect this. 
```
$ lxterm --images=images.json /dev/ttyUSBX --speed=1e6 --no-crc
```
to 
```
$ lxterm --images=buildroot/boot.json /dev/ttyUSBX --speed=1e6 --no-crc
```

**Comment by mescoba1** [comment]
I could be mistaken, looks like `images.json` and `buildroot.json` look similar. Can someone elaborate on the differences?

**Comment by enjoy-digital** [comment]
`images.json` is still used for serialboot, `boot.json` is used for netboot/sdcardboot. We could try to avoid having two separate files in the future, but for now the README is still up to date on this.

**Comment by mescoba1** [comment]
Thanks for the clarification
