### ISSUE TITLE
Selecting board variants

### ISSUE THREAD

**Issue by blitz** [litex-hub/linux-on-litex-vexriscv#155]
I have a ULX3S board with LFE5U-85F instead of LFE5U-45F FPGA.

Building the ULX3S variant results in a bit stream that is incompatible with this board. I've resorted to patching the litex-boards code to default to the 85F, but it would be nice if there is a straight-forward way to select the FPGA type.

**Comment by enjoy-digital** [comment]
With https://github.com/litex-hub/linux-on-litex-vexriscv/commit/fe8ad0926465ff6d110b5a3441e956e37b1eeb0b you can now do: `./make.py --board=ulx3s --device=LFE5U-85F --build`.

**Comment by blitz** [comment]
@enjoy-digital This is much appreciated. Thank you! :rocket:
