### ISSUE TITLE
LiteX SoC Controller Driver - linux problem

### ISSUE THREAD

**Issue by Chgavilana** [litex-hub/linux-on-litex-vexriscv#158]
Hi:
I did a working Linux binaries images for a Arty board with sdcard boot and ethernet driver (single and SMP) six month ago. However, I try to update the image and I got the follow message. I tried with buildroot for spinal_vexriscv_smp_defconfig and work, however this use a normal linux kernel that have not litex drivers patch, also driver for liteeth. When I use the repository from litex-hub/linux I get the error. Looking the message, I check the file litex_soc_crl.c and check LiteX CSR read/write access and I can not get a idea about the problem. I'm not sure if maybe could be related with issue #122 or maybe some update over vexriscv-smp folder. 

What do you think about could be the problem? 

> 
  --============== Boot ==================--

Booting from serial...
Press Q or ESC to abort boot completely.
sL5DdSMmkekro
[LXTERM] Received firmware download request from the device.
[LXTERM] Uploading /home/carlos/Documents/smp/buildroot/output/images/Image to 0x40000000 (6145908 bytes)...
[LXTERM] Upload complete (255.7KB/s).
[LXTERM] Uploading images/dtb to 0x40ef0000 (1898 bytes)...
[LXTERM] Upload complete (287.7KB/s).
[LXTERM] Uploading /home/carlos/Documents/smp/buildroot/output/images/rootfs.cpio to 0x41000000 (4069376 bytes)...
[LXTERM] Upload complete (255.9KB/s).
[LXTERM] Uploading images/fw_jump.bin to 0x40f00000 (45360 bytes)...
[LXTERM] Upload complete (256.1KB/s).
[LXTERM] Booting the device.
[LXTERM] Done.
KExecuting booted program at 0x40f00000

--============= Liftoff! ===============--

OpenSBI v0.6-1-g4ff0160
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|____/_____|
        | |
        |_|

Platform Name          : Litex/VexRiscv SMP
Platform HART Features : RV32AIMS
Platform Max HARTs     : 16
Current Hart           : 0
Firmware Base          : 0x40f00000
Firmware Size          : 180 KB
Runtime SBI Version    : 0.2

MIDELEG : 0x00000222
MEDELEG : 0x0000b101
[    0.000000] No DTB passed to the kernel
[    0.000000] Linux version 5.0.0 (carlos@LIGER) (gcc version 8.4.0 (Buildroot 2020.08-200-g88a268354d)) #7 SMP Sat Nov 14 18:26:14 -05 2020
[    0.000000] earlycon: sbi0 at I/O port 0x0 (options '')
[    0.000000] printk: bootconsole [sbi0] enabled
[    0.000000] Initial ramdisk at: 0x(ptrval) (8388608 bytes)
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000040000000-0x000000004fffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000040000000-0x000000004fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000040000000-0x000000004fffffff]
[    0.000000] elf_hwcap is 0x1101
[    0.000000] percpu: Embedded 10 pages/cpu @(ptrval) s18508 r0 d22452 u40960
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 65024
[    0.000000] Kernel command line: mem=256M@0x40000000 rootwait console=hvc0 earlycon=sbi root=/dev/ram0 init=/sbin/init
[    0.000000] Dentry cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Inode-cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Sorting __ex_table...
[    0.000000] Memory: 244592K/262144K available (4685K kernel code, 158K rwdata, 752K rodata, 178K init, 218K bss, 17552K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=2, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: 	RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=2.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=2
[    0.000000] NR_IRQS: 0, nr_irqs: 0, preallocated irqs: 0
[    0.000000] plic: mapped 32 interrupts to 4 (out of 4) handlers.
[    0.000000] clocksource: riscv_clocksource: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604467 ns
[    0.000098] sched_clock: 32 bits at 100MHz, resolution 10ns, wraps every 21474836475ns
[    0.003524] Console: colour dummy device 80x25
[    0.005020] Calibrating delay loop (skipped), value calculated using timer frequency.. 200.00 BogoMIPS (lpj=400000)
[    0.008261] pid_max: default: 32768 minimum: 301
[    0.011671] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.013867] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.031471] rcu: Hierarchical SRCU implementation.
[    0.039357] smp: Bringing up secondary CPUs ...
[    0.048391] smp: Brought up 1 node, 2 CPUs
[    0.055738] devtmpfs: initialized
[    0.074627] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.077678] futex hash table entries: 512 (order: 3, 32768 bytes)
[    0.082091] random: get_random_u32 called from bucket_table_alloc+0xa0/0x20c with crng_init=0
[    0.085545] NET: Registered protocol family 16
[    0.177666] FPGA manager framework
[    0.187487] clocksource: Switched to clocksource riscv_clocksource
[    0.315145] NET: Registered protocol family 2
[    0.325095] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes)
[    0.327957] TCP established hash table entries: 2048 (order: 1, 8192 bytes)
[    0.330255] TCP bind hash table entries: 2048 (order: 2, 16384 bytes)
[    0.332734] TCP: Hash tables configured (established 2048 bind 2048)
[    0.335546] UDP hash table entries: 256 (order: 1, 8192 bytes)
[    0.337423] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
[    0.343999] Unpacking initramfs...
[    0.845298] Initramfs unpacking failed: junk in compressed archive
[    0.856480] workingset: timestamp_bits=30 max_order=16 bucket_order=0
[    1.083551] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 253)
[    1.085640] io scheduler mq-deadline registered
[    1.087250] io scheduler kyber registered
[    1.093394] Kernel panic - not syncing: Scratch register read error! Expected: 0x12345678 but got: 0x78000000
[    1.096259] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 5.0.0 #7
[    1.097909] Call Trace:
[    1.098816] [<c002ee0c>] walk_stackframe+0x0/0xfc
[    1.100261] [<c002f040>] show_stack+0x3c/0x50
[    1.101632] [<c049e340>] dump_stack+0x84/0xb0
[    1.103006] [<c0033848>] panic+0x11c/0x28c
[    1.104320] [<c027f170>] litex_soc_ctrl_probe+0x200/0x210
[    1.105968] [<c02f5eb0>] platform_drv_probe+0x44/0x84
[    1.107517] [<c02f3ee4>] really_probe+0xd8/0x2a0
[    1.108938] [<c02f44dc>] driver_probe_device+0x4c/0x1dc
[    1.110517] [<c02f4784>] __driver_attach+0x118/0x130
[    1.112038] [<c02f2078>] bus_for_each_dev+0x74/0xb8
[    1.113522] [<c02f4938>] driver_attach+0x28/0x38
[    1.114949] [<c02f2c04>] bus_add_driver+0x1f8/0x224
[    1.116435] [<c02f512c>] driver_register+0x6c/0x154
[    1.117939] [<c02f6e2c>] __platform_driver_register+0x4c/0x5c
[    1.119695] [<c0012048>] litex_soc_ctrl_driver_init+0x24/0x34
[    1.121406] [<c0000de0>] do_one_initcall+0x64/0x14c
[    1.122904] [<c0001014>] kernel_init_freeable+0x14c/0x208
[    1.124527] [<c04ba2a8>] kernel_init+0x1c/0x11c
[    1.125941] [<c002db7c>] ret_from_exception+0x0/0x10
[    1.127425] SMP: stopping secondary CPUs
[    1.128737] ---[ end Kernel panic - not syncing: Scratch register read error! Expected: 0x12345678 but got: 0x78000000 ]---
>

**Comment by enjoy-digital** [comment]
Thanks @Chgavilana for the feedback, it has been fixed with https://github.com/litex-hub/linux-on-litex-vexriscv/commit/7b0c212b8051eb7416bbbd3c8826cf6625a4f80a. You just need to update the repository and rebuild the Arty design.
