### ISSUE TITLE
Non-admin installation of LiteX

### ISSUE THREAD

**Issue by abdullahyildiz** [litex-hub/linux-on-litex-vexriscv#160]
Installation guide asks to run `litex_setup.py install` with root privileges. Is it possible to install LiTeX with a non-admin user?

**Comment by enjoy-digital** [comment]
Hi @abdullahyildiz,

yes it's possible. I just updated the README with https://github.com/litex-hub/linux-on-litex-vexriscv/commit/8c9d5b077503c13e70f2224c5ed2e72e95f44659. For more information you can also visit: https://github.com/enjoy-digital/litex/wiki/Installation.
