### ISSUE TITLE
Test/Fix SDCard Linux Driver in SD-Mode

### ISSUE THREAD

**Issue by enjoy-digital** [litex-hub/linux-on-litex-vexriscv#171]
SDCard is currently working in SPI-Mode, SD-Mode should also be working (boot from SD-Card is already working) but still need to be tested/validated.

**Comment by kgugala** [comment]
@enjoy-digital what actually has to be tested? Linux support?

**Comment by pgielda** [comment]
It would really be great to get this sorted, this revert to spisdcard broke our internal Renode tests @enjoy-digital

**Comment by enjoy-digital** [comment]
@kgugala: yes that's the Linux support. If you can provide help testing it with current Linux kernel: https://github.com/litex-hub/linux-on-litex-vexriscv/blob/master/buildroot/configs/litex_vexriscv_defconfig#L26-L33 and current [litex_json2dts](https://github.com/enjoy-digital/litex/blob/master/litex/tools/litex_json2dts.py) this would be very useful: make sure it works and if not try to understand why, then share tested bitstream, images and steps so that I can reproduce the results (on Arty for example).

**Comment by enjoy-digital** [comment]
@pgielda: sorry if it broke your internal Renode tests, this has been reverted since issues were reported by users and I was lacking time on the moment to investigate. SDCard is now working but SDCard access is slower which is a temporary compromise. 

Note that Linux-on-LiteX-VexRiscv is an application project that can be used as an example to create Linux SoCs based on VexRiscv but I would not recommend having CI running directly based on it since it's important here to allow things to change/evolve.

**Comment by enjoy-digital** [comment]
From a discussion with @gsomlo on IRC, it seems the issue is reproduced on linux-on-litex-rocket project with 8-bit CSRs (32-bit CSRs is working fine).

**Comment by gsomlo** [comment]
On Mon, Dec 28, 2020 at 12:25:01PM -0800, enjoy-digital wrote:
> From a discussion with @gsomlo on IRC, it seems the issue is reproduced on
> linux-on-litex-rocket project with 8-bit CSRs (32-bit CSRs is working fine).

I tried to build the original Antmicro litesdcard driver from here:

https://github.com/litex-hub/linux/tree/wip/litex-vexriscv--linux5.0_sd_card_dma

for my 8-bit-csr-wide litex+rocket gateware. But even after the
hackery required to get it to probe, and updating the DMA base width
to 64 bit width to accomodate current litex defaults, it's not recognizing
the sdcard.

The modified/updated version I have in litex-rocket-rebase (and now in
litex-rebase) actually gets a bit further than the original even on
8-bit-csr (rocket) gateware.

https://github.com/litex-hub/linux/tree/litex-rebase

Not sure whether it was me who broke it (since I can't get the original
to work at all), or it's a mismatch w.r.t. the current litex gateware
(regardless of CPU) that causes it to fail on 8-bit csr-data-width.

But I think we might have an easier time debugging it from where we're
at (in litex-rebase), than trying to figure out where I might have broken
it for 8-bit-csr in the process of getting it to work for me in the first
place (on 32-bit csr litex+rocket).

So that's what I'm going to try, as soon as I have a few spare cycles
(unless anyone else beats me to it :).

**Comment by enjoy-digital** [comment]
This has been validated with VexRiscv-SMP, kernel generated from litex-rebase branch (5.11.0-rc2 ) and with `config-frequency `added to the `.dts`: https://github.com/enjoy-digital/litex/commit/b1cad93e62ecf57f1cd98489ca592dcf6d1cf3a2. 

SD-mode on boards has also been reverted with https://github.com/litex-hub/linux-on-litex-vexriscv/commit/732371976ece9a21e2490322f6f6c556232c9883.

Thanks a lot @gsomlo for suggesting looking at `config-frequency`.

**Comment by enjoy-digital** [comment]
Boot from SDCard on Arty and test of the SDCard under Linux:


```
        __   _ __      _  __
       / /  (_) /____ | |/_/
      / /__/ / __/ -_)>  <
     /____/_/\__/\__/_/|_|
   Build your hardware, easily!

 (c) Copyright 2012-2020 Enjoy-Digital
 (c) Copyright 2007-2015 M-Labs

 BIOS built on Jan 14 2021 08:55:48
 BIOS CRC passed (4464a638)

 Migen git sha1: d42aa6f
 LiteX git sha1: 83fb79fb

--=============== SoC ==================--
CPU:		VexRiscv SMP-LINUX @ 100MHz
BUS:		WISHBONE 32-bit @ 4GiB
CSR:		32-bit data
ROM:		64KiB
SRAM:		8KiB
L2:		0KiB
SDRAM:		262144KiB 16-bit @ 800MT/s (CL-6 CWL-5)

--========== Initialization ============--
Ethernet init...
Initializing SDRAM @0x40000000...
Switching SDRAM to software control.
Write latency calibration:
m0:0 m1:0 
Read leveling:
  m0, b0: |00000000000000000000000000000000| delays: -
  m0, b1: |00000000000011111111111111000000| delays: 19+-07
  m0, b2: |00000000000000000000000000001111| delays: 29+-02
  m0, b3: |00000000000000000000000000000000| delays: -
  m0, b4: |00000000000000000000000000000000| delays: -
  m0, b5: |00000000000000000000000000000000| delays: -
  m0, b6: |00000000000000000000000000000000| delays: -
  m0, b7: |00000000000000000000000000000000| delays: -
  best: m0, b01 delays: 19+-07
  m1, b0: |00000000000000000000000000000000| delays: -
  m1, b1: |00000000000011111111111111000000| delays: 19+-07
  m1, b2: |00000000000000000000000000001111| delays: 30+-02
  m1, b3: |00000000000000000000000000000000| delays: -
  m1, b4: |00000000000000000000000000000000| delays: -
  m1, b5: |00000000000000000000000000000000| delays: -
  m1, b6: |00000000000000000000000000000000| delays: -
  m1, b7: |00000000000000000000000000000000| delays: -
  best: m1, b01 delays: 19+-07
Switching SDRAM to hardware control.
Memtest at 0x40000000 (2MiB)...
  Write: 0x40000000-0x40200000 2MiB     
   Read: 0x40000000-0x40200000 2MiB     
Memtest OK
Memspeed at 0x40000000 (2MiB)...
  Write speed: 31MiB/s
   Read speed: 26MiB/s

--============== Boot ==================--
Booting from serial...
Press Q or ESC to abort boot completely.
sL5DdSMmkekro
Timeout
Booting from SDCard in SD-Mode...
Booting from boot.json...
Copying Image to 0x40000000 (7293192 bytes)...
[########################################]
Copying rv32.dtb to 0x40ef0000 (2069 bytes)...
[########################################]
Copying rootfs.cpio to 0x41000000 (4002304 bytes)...
[########################################]
Copying opensbi.bin to 0x40f00000 (53640 bytes)...
[########################################]
Executing booted program at 0x40f00000

--============= Liftoff! ===============--

OpenSBI v0.8-1-gecf7701
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|____/_____|
        | |
        |_|

Platform Name       : LiteX / VexRiscv-SMP
Platform Features   : timer,mfdeleg
Platform HART Count : 8
Boot HART ID        : 0
Boot HART ISA       : rv32imas
BOOT HART Features  : time
BOOT HART PMP Count : 0
Firmware Base       : 0x40f00000
Firmware Size       : 124 KB
Runtime SBI Version : 0.2

MIDELEG : 0x00000222
MEDELEG : 0x0000b101
[    0.000000] Linux version 5.11.0-rc2 (florent@panda) (riscv32-buildroot-linux-gnu-gcc.br_real (Buildroot 2020.11-281-g69e5046e7b) 10.2.0, GNU ld (GNU Binutils) 2.33.1) #2 SMP Mon Jan 11 10:05:20 CET 2021
[    0.000000] earlycon: sbi0 at I/O port 0x0 (options '')
[    0.000000] printk: bootconsole [sbi0] enabled
[    0.000000] Initial ramdisk at: 0x(ptrval) (8388608 bytes)
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000040000000-0x000000004fffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000040000000-0x000000004fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000040000000-0x000000004fffffff]
[    0.000000] SBI specification v0.2 detected
[    0.000000] SBI implementation ID=0x1 Version=0x8
[    0.000000] SBI v0.2 TIME extension detected
[    0.000000] SBI v0.2 IPI extension detected
[    0.000000] SBI v0.2 RFENCE extension detected
[    0.000000] SBI v0.2 HSM extension detected
[    0.000000] riscv: ISA extensions aim
[    0.000000] riscv: ELF capabilities aim
[    0.000000] percpu: Embedded 10 pages/cpu s18316 r0 d22644 u40960
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 65024
[    0.000000] Kernel command line: mem=256M@0x40000000 rootwait console=liteuart earlycon=sbi root=/dev/ram0 init=/sbin/init swiotlb=32
[    0.000000] Dentry cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] Inode-cache hash table entries: 16384 (order: 4, 65536 bytes, linear)
[    0.000000] Sorting __ex_table...
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 243800K/262144K available (5508K kernel code, 569K rwdata, 830K rodata, 209K init, 220K bss, 18344K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: 	RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=1.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] plic: cpu0: parent irq not available
[    0.000000] plic: interrupt-controller@f0c00000: mapped 32 interrupts with 1 handlers for 2 contexts.
[    0.000000] riscv-intc: 32 local interrupts mapped
[    0.000000] random: get_random_bytes called from start_kernel+0x360/0x4d0 with crng_init=0
[    0.000000] riscv_timer_init_dt: Registering clocksource cpuid [0] hartid [0]
[    0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0x171024e7e0, max_idle_ns: 440795205315 ns
[    0.000019] sched_clock: 64 bits at 100MHz, resolution 10ns, wraps every 4398046511100ns
[    0.004087] Console: colour dummy device 80x25
[    0.006085] Calibrating delay loop (skipped), value calculated using timer frequency.. 200.00 BogoMIPS (lpj=400000)
[    0.010138] pid_max: default: 32768 minimum: 301
[    0.015059] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.017742] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.043872] rcu: Hierarchical SRCU implementation.
[    0.051117] smp: Bringing up secondary CPUs ...
[    0.052715] smp: Brought up 1 node, 1 CPU
[    0.059647] devtmpfs: initialized
[    0.086397] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.090189] futex hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.096895] NET: Registered protocol family 16
[    0.258510] FPGA manager framework
[    0.272257] clocksource: Switched to clocksource riscv_clocksource
[    0.434233] NET: Registered protocol family 2
[    0.444456] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes, linear)
[    0.447671] TCP established hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.451032] TCP bind hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.454132] TCP: Hash tables configured (established 2048 bind 2048)
[    0.457341] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.460203] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.473842] Unpacking initramfs...
[    1.214270] Initramfs unpacking failed: invalid magic at start of compressed archive
[    1.263416] Freeing initrd memory: 8192K
[    1.273843] workingset: timestamp_bits=30 max_order=16 bucket_order=0
[    1.518248] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 253)
[    1.520930] io scheduler mq-deadline registered
[    1.522573] io scheduler kyber registered
[    1.534997] LiteX SoC Controller driver initialized: subreg:4, align:4
[    2.523479] f0001000.serial: ttyLXU0 at MMIO 0x0 (irq = 0, base_baud = 0) is a liteuart
[    2.529026] printk: console [liteuart0] enabled
[    2.529026] printk: console [liteuart0] enabled
[    2.531045] printk: bootconsole [sbi0] disabled
[    2.531045] printk: bootconsole [sbi0] disabled
[    2.564499] libphy: Fixed MDIO Bus: probed
[    2.566327] liteeth f0004800.mac: IRQ index 0 not found
[    2.567367] liteeth f0004800.mac: Failed to get IRQ, using polling
[    2.580320] liteeth f0004800.mac eth0: irq 0, mapped at a0407800
[    2.584692] i2c /dev entries driver
[    2.608219] litex-mmc f0005800.mmc: Requested clk_freq=12500000: set to 12500000 via div=8
[    2.655364] NET: Registered protocol family 10
[    2.670458] Segment Routing with IPv6
[    2.672545] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    2.696629] Freeing unused kernel memory: 204K
[    2.697579] Kernel memory protection not selected by kernel config.
[    2.698970] Run /init as init process
[    2.702044] litex-mmc f0005800.mmc: Requested clk_freq=0: set to 390625 via div=256
[    2.724580] litex-mmc f0005800.mmc: Requested clk_freq=12500000: set to 12500000 via div=8
[    2.767514] litex-mmc f0005800.mmc: Requested clk_freq=25000000: set to 25000000 via div=4
[    2.769532] mmc0: new SDHC card at address 0002
[    2.787158] blk_queue_max_hw_sectors: set to minimum 8
[    2.788615] blk_queue_max_segment_size: set to minimum 4096
[    2.789964] mmcblk0: mmc0:0002 N/A   29.8 GiB 
[    2.825065]  mmcblk0: p1
[    3.145871] tmpfs: Unknown parameter 'mode'
mount: mounting tmpfs on /dev/shm failed: Invalid argument
[    3.153874] tmpfs: Unknown parameter 'mode'
mount: mounting tmpfs on /tmp failed: Invalid argument
[    3.161813] tmpfs: Unknown parameter 'mode'
mount: mounting tmpfs on /run failed: Invalid argument
Starting syslogd: OK
Starting klogd: OK
Running sysctl: OK
Saving random seed: [    4.628100] random: dd: uninitialized urandom read (512 bytes read)
OK
Starting network: OK

Welcome to Buildroot
buildroot login: root
                   __   _
                  / /  (_)__  __ ____ __
                 / /__/ / _ \/ // /\ \ /
                /____/_/_//_/\_,_//_\_\
                      / _ \/ _ \
   __   _ __      _  _\___/_//_/         ___  _
  / /  (_) /____ | |/_/__| | / /____ __ / _ \(_)__ _____  __
 / /__/ / __/ -_)>  </___/ |/ / -_) \ // , _/ (_-</ __/ |/ /
/____/_/\__/\__/_/|_|____|___/\__/_\_\/_/|_/_/___/\__/|___/
                  / __/  |/  / _ \
                 _\ \/ /|_/ / ___/
                /___/_/  /_/_/
  32-bit RISC-V Linux running on LiteX / VexRiscv-SMP.

login[69]: root login on 'console'
root@buildroot:~# mount /dev/mmcblk0p1 /mnt
[ 1095.791299] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
root@buildroot:~# cd /mnt/
root@buildroot:/mnt# ls
Image                 boot.json             rootfs.tar
LINUX_~2.ZIP          dmesg.txt             rv32.dtb
OPENSBI.BIN           linux_2020_12_30.zip  uname_a.txt
OPENSBI.BIN           opensbi.bin
RV32.DTB              rootfs.cpio
root@buildroot:/mnt#
```

**Comment by zguig52** [comment]
Hi,
Don't know if this is the right place to give this info, but after loading the latest linux on ecpix5, I get this message every seconds:
[   11.953487] Command (cmd 8) failed, status 2
[   11.964504] Command (cmd 55) failed, status 2
[   11.975476] Command (cmd 55) failed, status 2
[   11.986474] Command (cmd 55) failed, status 2
[   11.997961] Command (cmd 55) failed, status 2
[   12.009593] Command (cmd 1) failed, status 2
[   12.011242] litex-mmc f0005000.mmc: Requested clk_freq=0: set to 273437 via div=256
[   13.067506] litex-mmc f0005000.mmc: Requested clk_freq=12500000: set to 8750000 via div=8

When I disable the sdcard option in the board, no problem at all. Please note that otherwise, linux is working fine.

**Comment by gsomlo** [comment]
That's probably because of the polling that's been enabled in the
driver:

https://github.com/litex-hub/linux/blob/c926b7e5819cf8050d17400e770cb955634f58b7/drivers/mmc/host/litex_mmc.c#L446

combined with the lack of a card-detect pin on the ecpix5's sdcard
pads:

https://github.com/litex-hub/litex-boards/blob/master/litex_boards/platforms/ecpix5.py#L93

(Contrast with, e.g., nexys4ddr, which *does* have a "cd" pin:
https://github.com/litex-hub/litex-boards/blob/master/litex_boards/platforms/nexys4ddr.py#L83
)

In the cd-pin-less scenario, the litesdcard gateware returns "present"
by default, which means linux thinks there should be a card in the
socket, and attempts to initialize it, and you see those log entries
when that initialization fails (because there's really no card present)

There might be a way to use gpio to signal the driver whether a card
is present or not. There might actually exist a bona-fide cd pin on
the ecpix5 that hasn't been added to the platform file (probably not,
but I've seen it happen on other platforms).

Either way, the "easiest" solution is to treat your sd card as
"non-removable", have it inserted at boot, and don't ever eject
(because as it is right now, the linux driver can't tell the
difference, and has to assume the card is always plugged in).

HTH,
--Gabriel

**Comment by zguig52** [comment]
This seems to be a very good reason, thanks Gabriel. I will try to find one and put it in to confirm.
Maybe also, we can fix the board conf, there is a cd pin on port L22?
http://docs.lambdaconcept.com/ecpix-5/features/microsd.html
`microSD card pin | FPGA pin | Description
-- | -- | --
CMD | M24 | Command/response
CLK | P24 | Clock
CD | L22 | Card Detect
DAT0 | N26 | Data line (bit 0)
DAT1 | N25 | Data line (bit 1)
DAT2 | N23 | Data line (bit 2)
DAT3 | N21 | Data line (bit 3)
D0+ | AD19 | UHS-II lane 0 (Positive)
D0- | AD20 | UHS-II lane 0 (Negative)
D1+ | AF18 | UHS-II lane 1 (Positive)
D1- | AF19 | UHS-II lane 1 (Negative)`

**Comment by zguig52** [comment]
Hey Gabriel, your point was totally right! Thanks again!

When I added to line 97:
'Subsignal("cd",        Pins("L22")),'

Everything is working fine:

litex> sdcard_detect
SDCard not inserted.

... put an SDCard

litex> sdcard_detect
SDCard inserted.

Rebooted to load linux and no more error message :)

It is properly detecting SDCard insertion / removal:
[   45.863892] litex-mmc f0005000.mmc: Requested clk_freq=0: set to 273437 via div=256
[   45.883607] litex-mmc f0005000.mmc: Requested clk_freq=12500000: set to 8750000 via div=8
[   45.999188] litex-mmc f0005000.mmc: Requested clk_freq=25000000: set to 35000000 via div=2
[   46.000838] mmc0: new SDHC card at address 0007
[   46.023843] blk_queue_max_hw_sectors: set to minimum 8
[   46.024811] blk_queue_max_segment_size: set to minimum 4096
[   46.026116] mmcblk0: mmc0:0007 SD16G 14.5 GiB 
[   46.068268]  mmcblk0: p1 p2
[   51.209503] Command (cmd 13) failed, status 2
[   51.220409] Command (cmd 13) failed, status 2
[   51.231305] Command (cmd 13) failed, status 2
[   51.242192] Command (cmd 13) failed, status 2
[   51.253797] Command (cmd 13) failed, status 2
[   51.265192] Command (cmd 13) failed, status 2
[   51.276082] Command (cmd 13) failed, status 2
[   51.287069] Command (cmd 13) failed, status 2
[   51.297955] Command (cmd 13) failed, status 2
[   51.309520] Command (cmd 13) failed, status 2
[   51.310503] mmc0: card 0007 removed
[   51.392703] litex-mmc f0005000.mmc: Requested clk_freq=0: set to 273437 via div=256

Still a small error message when removing it: Command (cmd 13) failed, status 2, put not persistent. I don't know if this is normal?

If it is OK, I will try to push this fix.

**Comment by gsomlo** [comment]
I think the failed cmd13 attempts following a removal are normal.
Please go ahead and submit a PR for the CD pin on the ecpix5.

Best,
--Gabriel
