### ISSUE TITLE
camlink_4k: multiple IOs on same cell

### ISSUE THREAD

**Issue by devobliquezer0** [litex-hub/linux-on-litex-vexriscv#188]
command: `./make.py --board=camlink_4k --cpu-count=1 --build`

error: `ERROR: Cell 'serial_tx$tr_io' cannot be bound to bel 'X4/Y0/PIOA' since it is already bound to cell 'user_led0$tr_io'`

**Comment by enjoy-digital** [comment]
Thanks for the feedback, this is fixed by https://github.com/litex-hub/litex-boards/commit/d256cc8bd62f874df9c99809113c5ec87794f0b8.
