### ISSUE TITLE
Illegal instruction on a simple binary

### ISSUE THREAD

**Issue by pcotret** [litex-hub/linux-on-litex-vexriscv#193]
Hi,
I'm trying to execute a custom binary with pre-built Linux binaries + Nexys4DDR. In other words, my goal is to boot the existing Linux stack and execute a custom binary afterwards (a good old `hello world` for instance).

My C code:
```c
int main()
{
    int a=3,b=7,c=3;
    c=a+b;
    return 0;
}
```
Compile it with:
```bash
riscv64-unknown-elf-gcc -march=rv32im -mabi=ilp32 main.c -o main
```
After copying the binary on my SD card, if I execute `main`, I get an "Illegal instruction".

- Am I missing something in the compilation process?
- Is it the recommended method to run a binary on this Linux distro?
EDIT : I think I forgot to use a correct linker script, right ?

**Comment by pcotret** [comment]
I'm gonna close my own issue.
I've been able to do what I want by putting my binary in the `rootfs_overlay` directory.

**Comment by enjoy-digital** [comment]
@pcotret: good you've been able to do what you wanted.  Sorry for not  being responsive on this.
