### ISSUE TITLE
Error at ./sim.py in "Running litex simulation"

### ISSUE THREAD

**Issue by jhu960213** [litex-hub/linux-on-litex-vexriscv#204]
Hello,

Each step of the: https://github.com/litex-hub/linux-on-litex-vexriscv works fine up until when I run: ./sim.py. Running the litex simulation of the linux kernel gave me these outputs. Please see attached outputs.  

![Screenshot from 2021-03-04 18-27-32](https://user-images.githubusercontent.com/20133323/110045601-ed5e4f00-7d18-11eb-952f-c4e037756932.png)
![Screenshot from 2021-03-04 17-41-23](https://user-images.githubusercontent.com/20133323/110045608-f0593f80-7d18-11eb-9ff2-f3129517cafb.png)
![Screenshot from 2021-03-04 18-41-52](https://user-images.githubusercontent.com/20133323/110045864-580f8a80-7d19-11eb-92f3-1ac87bd61be2.png)

I've looked into the source code and apparently in the "linux-on-litex-vexriscv/images" folder was missing 3 files:
1) Image
2) rootfs.cpio
3) opensbi.bin

However, rv32.dtb is there. The branch where I cloned the project was from the master branch if that matters. 

I'm not sure if those 3 files are supposed to be there or not but when I created dummy ones the error during compilation is gone then I get stuck at the  "Lift-Off!" part:

![Screenshot from 2021-03-04 18-47-00](https://user-images.githubusercontent.com/20133323/110046453-09aebb80-7d1a-11eb-8292-6e89a9cb9685.png)

I'm running ubuntu 20.04.2 LTS if this helps

Thanks!

Best,
J.H

**Comment by geertu** [comment]
Please find prebuilt images in #164.

**Comment by enjoy-digital** [comment]
@jhu960213: Booting the simulation up to the Linux prompt can take some time yes, between 5-10 min depending your computer, unpacking initramfs is indeed a long step.

**Comment by hasheddan** [comment]
@jhu960213 confirmed initramfs takes quite a while locally but should eventually pass if not showing any errors

**Comment by enjoy-digital** [comment]
I think we can now close this, the error reporting in get_mem_data has been improved a bit with https://github.com/enjoy-digital/litex/commit/a81d1da98008e450cb8b11a4c9b9c379c1124fcd.
