### ISSUE TITLE
Loading bit stream error for kc705 board

### ISSUE THREAD

**Issue by jhu960213** [litex-hub/linux-on-litex-vexriscv#207]
Hello,

I was able to build properly for the kc705 board for the Linux on vexriscv project but was unable to load the bitstream by running the command:

./make.py --board=kc705 --cpu-count=4 --load

I don't really understand what the debug output is referring and I feel like it might be a simple issue or permissions thing I've overlooked. Attached below is the debug output. 

![Screenshot from 2021-03-08 18-19-14](https://user-images.githubusercontent.com/20133323/110395029-6cb29200-803b-11eb-99ce-1fa7eb1f585d.png)

please advise :) Thanks! 

P.S: I'm running ubuntu 20.04TS 64bit

Best,
J.H

**Comment by jhu960213** [comment]
@enjoy-digital

**Comment by enjoy-digital** [comment]
Hi @jhu960213,

this could be related to a change in OpenOCD. Can you try with this version: https://github.com/enjoy-digital/openocd? Also if you really have trouble with OpenOCD, you can use Vivado GUI and the Hardware Manager.

**Comment by jhu960213** [comment]
@enjoy-digital 
Hello,

So I tried building with that version of opened and I ran into a lot of build errors when I was trying to install openocd. Also I noticed that the enjoy-digital's version is very old. 

Best,
J.H

**Comment by enjoy-digital** [comment]
@jhu960213: OK, can you try loading the bistream with Vivado?

**Comment by jhu960213** [comment]
Hello @enjoy-digital 

I was finally able to load the bit stream in the end to board = kc705 :). It was a permission issue with opencd, I added myself to the etc/udev/rules.d for accessing linux peripherals over Jtag/USB. But now I have a question, it seems like its taking a while to load the linux kernel over serial/Jtag. Is this the expected behaviour? Also this is the command I used:

![Screenshot from 2021-03-11 17-11-53](https://user-images.githubusercontent.com/20133323/110862137-1d63a000-828d-11eb-8395-10bfb8b4d03a.png)

Do you guys seem a problem with how I configured the /dev/ttyUSBX part? How do I know which usb port my fpga is connected to? 

Thanks! 

Best,
J.H

**Comment by jhu960213** [comment]
Hello @enjoy-digital 

So indeed when I run the lxterm command, the bios doesn't boot up or show any outputs at all. It just hangs there. Please advise, I'm sure how to go from here. 

![Screenshot from 2021-03-11 17-11-53](https://user-images.githubusercontent.com/20133323/110976792-5c4a3200-832f-11eb-8c0b-4bb6c87011f8.png)

Best,
J.H

**Comment by enjoy-digital** [comment]
Hi @jhu960213,

the UART is not capable of 1MBauds on the KC705, to it has been reduced to 500KBauds (--speed=500e3).

**Comment by jhu960213** [comment]
@enjoy-digital 
Hello,

I tried it with the new speed but I still get stuck with no outputs and bios prompt. 

J.H

**Comment by jhu960213** [comment]
Hello @enjoy-digital 

So i was able to load the linux image in the end with the lxterm command (I was using a wrong usb port and didnt have read/write persmission on it etc) but now when it finished booting up it sort of repeatedly prints out these debug outputs to console... Only when i hit enter it brings it back to a normal linux commandline style shown below but if I don't hit enter anymore it will just keep on printing these values. What's going on? 

![Screenshot from 2021-03-12 15-27-43](https://user-images.githubusercontent.com/20133323/110995191-ea321700-8347-11eb-892e-9341b7c109b6.png)

I'm running linux on the KC705 board fyi. 

Thanks!
J.H

**Comment by zhuzhizhan** [comment]
Hi, 
I have the same problem in nexys4ddr. I have solved it with: 1.remove the file with the ft2232h info in /etc/udev/rules.d/. 2.touch 99-openocd.rules with info "SUBSYSTEM=="tty", ATTRS{idVendor}=="0403",ATTRS{idProduct}=="6010", MODE="664", GROUP="plugdev"
SUBSYSTEM=="tty", ATTRS{idVendor}=="15ba",ATTRS{idProduct}=="002a", MODE="664", GROUP="plugdev"
SUBSYSTEM=="usb", ATTR{idVendor}=="0403",ATTR{idProduct}=="6010", MODE="664", GROUP="plugdev"
SUBSYSTEM=="usb", ATTR{idVendor}=="15ba",ATTR{idProduct}=="002a", MODE="664", GROUP="plugdev""
3.build the openocd with  https://github.com/enjoy-digital/openocd.

**Comment by enjoy-digital** [comment]
I think we can now close this issue since the initial problem has been solved. For the SDCard issue, LiteSDCard core and drivers have been udpated since then and are working fine on other hardware, so it would need to be tested again.

**Comment by zhuzhizhan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
