### ISSUE TITLE
booting linux on zcu104

### ISSUE THREAD

**Issue by zld932** [litex-hub/linux-on-litex-vexriscv#213]
hello
The bitstream for zcu104 has been generated. And I have load the bitstream using the following command successfully.
./make.py --board=zcu104 --cpu-count=1 --load

but when I run lxterm, the bios doesn't boot up or show any outputs. It just hangs there. 

![Screenshot from 2021-03-15 15-29-20](https://user-images.githubusercontent.com/68100093/111118714-1e097880-85a4-11eb-83f1-3d0cf913499b.png)

what can I do to run linux, or how do I configure zcu104 to run
Thanks

**Comment by DWhitey** [comment]
Hi, I have the same issue at the moment. I built the bitsream and loaded it successfully. What did you do that lxterm doesn't get stuck?
Thanks

**Comment by zld932** [comment]
> Hi, I have the same issue at the moment. I built the bitstream and loaded it successfully. What did you do that lxterm doesn't get stuck?
> 
> Thanks

ZCU104 has more than one port. So try other ports when you use lxterm. When you are struck, press enter. When you have response which  is same with terminal, type in reboot. 
Best wishes.

**Comment by zld932** [comment]
> Hi, I have the same issue at the moment. I built the bitstream and loaded it successfully. What did you do that lxterm doesn't get stuck?
> 
> Thanks

The speed is 1e6

**Comment by DWhitey** [comment]
> When you are struck, press enter.

Hi, thanks for your answer. That helped me. Well, I forgot to add a DIMM as well..
