### ISSUE TITLE
Ethernet for zcu104

### ISSUE THREAD

**Issue by zld932** [litex-hub/linux-on-litex-vexriscv#216]
hello,
I have successfully built the bitstream for zcu104, and running linux on zcu104 through serial port is also successful. But there is no network in linux system. By running " ip addr ", no "eth0" occured.

**Comment by enjoy-digital** [comment]
Hello @zld932,

thanks for the feedback. The 1Gbps RGMII PHY is connected to the PS on the ZCU104 and I'm not sure it's possible connect to it directly from the PL: https://forums.xilinx.com/t5/Ethernet/ZCU-104-Ethernet-Configurations/td-p/928803.

Interconnecting the 1Gbps RGMII PHY with the LiteX SoC would be possible but will not be as simple as on other boards. Antmicro is using the ZCU104 with a LiteX SoC and created a minimal software on the Zynq to do a bridge between Ethernet and the SoC: https://github.com/antmicro/litex-rowhammer-tester/tree/master/firmware/zcu104.

As stated on the Xilinx forum, the easiest way would probably to use an Ethernet FMC. (For fast Linux boot, you could also use the onboard SDCard if accessible from the PL.)
