### ISSUE TITLE
"switches_interrupt"

### ISSUE THREAD

**Issue by chris9870** [litex-hub/linux-on-litex-vexriscv#239]
Hi

What makes "KeyError: 'switches_interrupt"?
I compiled with "--board=arty_a7 --build --load". build finished without any issues.

Thanks
Chris

Size               16M
Start Address      0x00000000
End Address        0x00FFFFFF

Addr1         Addr2         Date                    File(s)
0x00000000    0x0021728B    Jul  8 11:39:18 2021    arty_a7.bit
0 Infos, 0 Warnings, 0 Critical Warnings and 0 Errors encountered.
write_cfgmem completed successfully
# quit
INFO: [Common 17-206] Exiting Vivado at Thu Jul  8 11:39:27 2021...
Traceback (most recent call last):
  File "./make.py", line 662, in <module>
    main()
  File "./make.py", line 643, in main
    soc.generate_dts(board_name)
  File "/home/chris9870/LiteX/linux-on-litex-vexriscv/soc_linux.py", line 194, in generate_dts
    dts_content = generate_dts(json.load(json_file), polling=False)
  File "/home/chris9870/LiteX/litex/litex/tools/litex_json2dts.py", line 418, in generate_dts
    switches_interrupt = "" if polling else "interrupts = <{}>;".format(d["constants"]["switches_interrupt"]))
KeyError: 'switches_interrupt'"

**Comment by enjoy-digital** [comment]
Thanks @chris9870 for the feedback, this has been fixed with #242.
