### ISSUE TITLE
Decreasing system clock speed for the Nexys Video board

### ISSUE THREAD

**Issue by chriswils95** [litex-hub/linux-on-litex-vexriscv#240]
I am trying to boot linux on the Nexys Video board using a clock frequency of 50Mhz. In other to achieve this, i edit the nexys_video class in make.py and add the soc_kwargs as shown below. For some reason i cannot boot the linux image through sdcard. Error message is also attached.

Make.py:
class NexysVideo(Board):
    soc_kwargs = {
        "sys_clk_freq" : int(50e6), # decrease sys_clk_freq to 50MHz (100MHz default).
    }
    def __init__(self):
        from litex_boards.targets import nexys_video
        Board.__init__(self, nexys_video.BaseSoC, soc_capabilities={
            # Communication
            "usb_fifo",
            # Storage
            "sdcard",
            # Video
            "framebuffer",
        }, bitstream_ext=".bit")
![error](https://user-images.githubusercontent.com/65049496/125518460-0f6d9b16-3225-40e7-8f71-686659f5a578.png)

**Comment by enjoy-digital** [comment]
Hi @chriswils95,

I would recommend keeping the default clock. The issue with the low clock frequency is probably similar to https://github.com/litex-hub/litex-boards/issues/166, you can probably try the same workaround until we improve Artix7 support at lower frequencies.
