### ISSUE TITLE
There is no ethphy in kcu105, only ethmac.

### ISSUE THREAD

**Issue by benoit1995** [litex-hub/linux-on-litex-vexriscv#244]
I successfully downloaded the kernel (https://github.com/litex-hub/linux-on-litex-vexriscv/issues/164) to kcu105 using tftp, but I don't see eth0 after using ifconfig -a, only Io and sit0 exist.
![image](https://user-images.githubusercontent.com/58306659/129169447-65a862df-6159-4eeb-b48f-57ac88c17487.png)
I checked . /build/kcu105/kcu105.dts, found no mac0 node, then in litex/tools/litex_json2dts.py I found that if I want to generate a mac0 node, I need both ethphy and ethmac.
`if "ethphy" in d["csr_bases"] and "ethmac" in d["csr_bases"]:`
I found that when enabling the ethernet of kcu105 in make.py, it only generates ethmac but not ethphy.
![image](https://user-images.githubusercontent.com/58306659/129169910-cfa18f51-83fb-49c6-acdb-60721c5e0401.png)
![image](https://user-images.githubusercontent.com/58306659/129169969-98b44ca3-0a61-4524-8ba9-f57dfe352737.png)
Why does this situation arise? Is it because kcu105 is using sfp instead of rj45?
Looking forward to your reply.

Benoit.

**Comment by enjoy-digital** [comment]
Thanks @benoit1995 for the feedback. The 1000 BASE X PHY used on the KCU105 is indeed a bit different and currently does not have CSRs. I'll look at this soon.

**Comment by enjoy-digital** [comment]
Sorry for the delay, this is fixed by https://github.com/enjoy-digital/liteeth/commit/4cd0a99187677553078fcefbf78eb15863b6ed61.
