### ISSUE TITLE
`sim.py`: SoCSDRAM is deprecated

### ISSUE THREAD

**Issue by tkphd** [litex-hub/linux-on-litex-vexriscv#245]
`sim.py` warns:

```bash
$ ./sim.py 
Compat: SoCSDRAM is deprecated since 2020-03-24 and will soon no longer work, please update.
        Switch to SoCCore/add_sdram/soc_core_args instead...........thanks :)
```

**Comment by enjoy-digital** [comment]
Thanks @tkphd, the code was already up to date this was caused by the import that has been removed with https://github.com/litex-hub/linux-on-litex-vexriscv/commit/94f5eb58a94f562d6f45c318de6c975daa3c3ec4.
