### ISSUE TITLE
Incorrect kernel version in defconfig

### ISSUE THREAD

**Issue by developandplay** [litex-hub/linux-on-litex-vexriscv#246]
When I try build the Linux version for Vexriscv I'm getting this issue:
```Incorrect selection of kernel headers: expected 5.13.x, got 5.12.x```

**Comment by developandplay** [comment]
I was able to resolve the problem by using the latest https://github.com/litex-hub/linux/tree/litex-vexriscv-rebase version of Linux.
@enjoy-digital Not sure if the preferred approach would be to point this to one specific commit and update it every now and then or to just point it at the litex-vexriscv-rebase branch.

**Comment by sajattack** [comment]
I solved the same issue by doing a menuconfig of the buildroot and setting the kernel header version to 5.12.x
