### ISSUE TITLE
Run ./sim.py errors

### ISSUE THREAD

**Issue by Flywing2018** [litex-hub/linux-on-litex-vexriscv#251]
I have cloned the repo(linux-on-litex-vexriscv) and setup/build/run sim.py sucessful on Ubuntu20.04.
Then I try to repeat these on RHEL8, I have overcome many packages difference between 2 OSs, finally, it failed at sim.py running.
It showed errors on terminal, it seems python throw exception due to didn't get correct parameters. Does anyone encounter similar problems?
![Linux_on_Vexriscv_sim](https://user-images.githubusercontent.com/35586591/139777594-e9f953fe-2567-424a-9c70-b6f0bd714bff.png)

**Comment by enjoy-digital** [comment]
Closing since no update and related to an installation issue.
