### ISSUE TITLE
UL3S LFE5U-85F version  support

### ISSUE THREAD

**Issue by imuguruza** [litex-hub/linux-on-litex-vexriscv#276]
I am trying to load the bitstream to my ULX3S board and i got the next message:
```
Found LFE5U-85F device, but the bitstream is for LFE5U-45F.

```

Can I synth somehow for this part number instead of the 45F?
Thanks!

**Comment by enjoy-digital** [comment]
This should work: `./make.py --board=ulx3s --device=LFE5U-85F --build --load`.

**Comment by imuguruza** [comment]
Ok, let my try it :)

**Comment by enjoy-digital** [comment]
Closing this, please re-open if not working :)
