### ISSUE TITLE
readme needs udev

### ISSUE THREAD

**Issue by CarlFK** [litex-hub/linux-on-litex-vexriscv#28]
./make.py --board=arty --load
 Error: libusb_open() failed with LIBUSB_ERROR_ACCESS

```
git clone https://github.com/litex-hub/litex-buildenv-udev
cd litex-buildenv-udev
make install
make reload
```

**Comment by enjoy-digital** [comment]
Thanks, fixed with https://github.com/litex-hub/linux-on-litex-vexriscv.
