### ISSUE TITLE
Running OpenMP code

### ISSUE THREAD

**Issue by ashuthosh-mr** [litex-hub/linux-on-litex-vexriscv#281]
Hi, I wish to run OpenMP benchmark codes on a RISC-V multi-core platform. Is it possible on Vexriscv SMP since it has a runtime environment through this project? If not, are there any other ways somewhere else? Thank you

**Comment by Dolu1990** [comment]
maybe via buildroot rebulding a image with the packages ? but i realy have no idea

**Comment by ashuthosh-mr** [comment]
Hi, an update on this issue. In the config litex_vexriscv_def_config, under the section of gcc, I added these lines(found it in the issue  #271 ):
# GCC
BR2_GCC_VERSION_10_X=y
BR2_GCC_ENABLE_OPENMP=y
BR2_INSTALL_LIBSTDCPP=y
BR2_TOOLCHAIN_BUILDROOT_CXX=y

The above lines are not present in the default config file.
Rebuilt the buildroot images from scratch. It generated toolchains to compile that supported shared libraries such as libgomp.so.1
Now I am able to run openmp codes. Thank you.

**Comment by Dolu1990** [comment]
Hooo nice, thanks for the feedback ^^
