### ISSUE TITLE
tab completion drawing odd

### ISSUE THREAD

**Issue by CarlFK** [litex-hub/linux-on-litex-vexriscv#30]
Running the LiteX simulation
$ ./sim.py

login.. use tab completion, something happens - dupes the line?

```
root@buildroot:~# cat /proc/cpuin <tab>
root@buildroot:~# cat /proc/cpuinroot@buildroot:~# cat /proc/cpuinfo
```

**Comment by enjoy-digital** [comment]
Switching LiteX UART driver fixed it: https://github.com/litex-hub/linux-on-litex-vexriscv/commit/4c138aef31a878be2d8454956cec3ef505191bc3
