### ISSUE TITLE
litex_term CRC error on Orangecrab without --safe

### ISSUE THREAD

**Issue by edwintorok** [litex-hub/linux-on-litex-vexriscv#304]
The `litex_term` command given here doesn't work on OrangeCrab r0.2.1 85F.
See https://github.com/enjoy-digital/litex/issues/773#issuecomment-778697382, `sfl_outstanding` has to be set to 0, or in the latest version using `--safe`.
So this command worked on the Orangecrab for me:
`litex_term --images=images/boot.json /dev/ttyACM0 --safe`

With this it loads the image just fine, whereas by default it fails with a CRC error every time.

**Comment by enjoy-digital** [comment]
Thanks @edwintorok, I just added a precision in the README for this with https://github.com/litex-hub/linux-on-litex-vexriscv/commit/d03b3a4a4c34a3a061e45124763737e0222ef2e7.
