### ISSUE TITLE
readme need another sudo

### ISSUE THREAD

**Issue by CarlFK** [litex-hub/linux-on-litex-vexriscv#31]
https://github.com/litex-hub/linux-on-litex-vexriscv#installing-verilator-only-needed-for-simulation

```
$ apt install verilator
$ apt install libevent-dev libjson-c-dev
```

**Comment by enjoy-digital** [comment]
Thanks, added with tps://github.com/litex-hub/linux-on-litex-vexriscv/commit/6724c9a7fc1d1079df094d593785d1e45f931055.
