### ISSUE TITLE
Linux in simulation

### ISSUE THREAD

**Issue by hparpinel** [litex-hub/linux-on-litex-vexriscv#318]
How long should it takes to run Linux in simulation?
I am running the ./sim.py and it seems to be stuck at   [ 0.665874] io scheduler kyber registered
is there something I should do or just let it run?

**Comment by Dolu1990** [comment]
some time, there could be ~1 seconds of simulated time between linux consol messages, so, like 15 mn of  simulation time

**Comment by hparpinel** [comment]
Once I flash the board with Linux how can I check the speed of the CPU? I tried using  the command nmeter but it throws the error command not found

**Comment by Dolu1990** [comment]
hmm by speed you mean frequency ? or performance ? If you need binaries, you need to enable them in buildroot and regenerate the rootfs

**Comment by enjoy-digital** [comment]
@hparpinel: As pointed by @Dolu1990, with buildroot, you'll have to select/install the packages you are used to on regular distro manually.  @Dolu1990 got Debian support working for NaxRiscv (64-bit) and @gsomlo got Fedora support on Rocket (64-bit) so we should be able to provide convenient alternatives soon for developers willing to use regular distros.
