### ISSUE TITLE
Same design not working on identical boards

### ISSUE THREAD

**Issue by Beauxrel** [litex-hub/linux-on-litex-vexriscv#323]
I am working on porting a new board (VCU108) and have 2 identical boards, for some reason the design / bitstream works on one board and allows me to load into linux. But the other board is freezing / hanging at Liftoff (Shown below). I have tried fixing timing issues and the design runs in Vivado show timing is being made, however I have suspicions about the timing wizard and asynchronous clocks. What could be the issue?

///////////////////////
Non-Working Board
///////////////////////
![image](https://user-images.githubusercontent.com/65138996/214874071-ac37e433-9d7f-4137-b32c-31c2b7fb78ad.png)
![image](https://user-images.githubusercontent.com/65138996/214875578-094fb70c-9a3e-464f-9ea2-f5b625cc24ec.png)

///////////////////////
Working Board
///////////////////////
![image](https://user-images.githubusercontent.com/65138996/214874213-de092f54-b468-429f-89ab-7891f2aedffe.png)
![image](https://user-images.githubusercontent.com/65138996/214874236-759dba73-27f4-4c61-a776-c27bac4ad9d4.png)

**Comment by enjoy-digital** [comment]
Hi @Beauxrel,

could you share the full LiteX BIOS prompt for the two boards? I would like to have a closer look at the DRAM calibration and compare it between boards.

**Comment by enjoy-digital** [comment]
Closing since no feedback and/or hardware available.

**Comment by Beauxrel** [comment]
@enjoy-digital This was a board issue. I had to RMA the board!

**Comment by enjoy-digital** [comment]
@Beauxrel: Ah OK, good to know, thanks for the feedback.
