### ISSUE TITLE
build/sim/sim.dts:78.13-98.11: ERROR (phandle_references): /soc: Reference to non-existent node or label "intc0"

### ISSUE THREAD

**Issue by quantrpeter** [litex-hub/linux-on-litex-vexriscv#329]
![Screenshot from 2023-03-04 15-24-49](https://user-images.githubusercontent.com/50471577/222882124-e5c144ee-f034-46c6-b5f7-adfaef4174c2.png)

and meson seem has error:

![Screenshot from 2023-03-04 15-25-46](https://user-images.githubusercontent.com/50471577/222882162-1e9c8b82-0649-4ad2-a98e-7950f74c64b2.png)

thanks

**Comment by quantrpeter** [comment]
![image](https://user-images.githubusercontent.com/50471577/223706395-970ad92f-a0ee-4c28-802c-515a977a04bf.png)

**Comment by enjoy-digital** [comment]
Thanks @quantrpeter, this was a regression introduced when adding Rocket support in the json2dts script, this is fixed with https://github.com/enjoy-digital/litex/commit/7bd98cf5d974799528f1b4441fd39425fd9c4c2e.

**Comment by quantrpeter** [comment]
thank you, it works now
