### ISSUE TITLE
Unsupported ISA substring '2p0_ma'

### ISSUE THREAD

**Issue by kaminto-1999** [litex-hub/linux-on-litex-vexriscv#333]
I ran into this trouble when running ./sim.py.
When I check the meson-logs.txt file, I got this message:
![image](https://user-images.githubusercontent.com/84948579/227450821-76e85a6a-daf4-474a-941b-5768420d6a13.png)
Is there anyone having the same problem as me? Or known how to fix it
Thank a lot !

**Comment by Dolu1990** [comment]
Hi, Which version of riscv64-unknown-elf-gcc do you have ?

**Comment by Dolu1990** [comment]
What do you get if you do riscv64-unknown-elf-gcc  --version ?

**Comment by kaminto-1999** [comment]
> What do you get if you do riscv64-unknown-elf-gcc --version ?
It said that v8.1.0.
I got this version when running this command "wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.1.0-2019.01.0-x86_64-linux-ubuntu14.tar.gz"
![image](https://user-images.githubusercontent.com/84948579/227702434-542dc772-2f1a-4fb7-ad63-7d30212ed998.png)

**Comment by kaminto-1999** [comment]
I have updated RISC-V Toolchain from SiFive compiler and it can run through the error at this moment.
But my terminal will close after running for a while.
It always stop at this nofication
![image](https://user-images.githubusercontent.com/84948579/227705800-3710e15e-c7ce-43e9-8ade-f0c62486110b.png)
