### ISSUE TITLE
litex vexriscv cpu-variant linux not starting

### ISSUE THREAD

**Issue by AnttiLukats** [litex-hub/linux-on-litex-vexriscv#34]
LiteX build seems working properly, 4 different new platforms did all come alive instantly, but in all cases as soon as the cpu-variant is changed from "full" to "linux" then the BIOS prompt does not come any more:
cyclone10LP target (quartus 18.1) - no uart output with "linux" variant
artix-7 target (vivado 2018.3 or 2019.1) - about 10 first characters come out, then stop

any suggestions what can be the issue? I will try to get some more boards and do more testing, but seems weird that until "full" all variants always work with no issues, and then dead comes

**Comment by enjoy-digital** [comment]
Can you do a test with the linux variant using this mem_map:
https://github.com/litex-hub/linux-on-litex-vexriscv/blob/master/soc_linux.py#L25-L33
instead of:
https://github.com/enjoy-digital/litex/blob/master/litex/soc/integration/soc_core.py#L142-L147
?

**Comment by AnttiLukats** [comment]
not sure if I did it right:

class BaseSoC(SoCCore):

    mem_map = {
       "rom":          0x00000000,
       "sram":         0x10000000,
       "emulator_ram": 0x20000000,
       "main_ram":     0xc0000000,
       "csr":          0xf0000000,
    }
    mem_map.update(SoCCore.mem_map)

    def __init__(self, sys_clk_freq=int(100e6), **kwargs):
        platform = te0711.Platform()

this at least made no change, it is all working with variant=full and with variant=linux there comes out about 10 characters from the LiteX logo

"        __"
first 10 chars of greeting are printed then no further output..

**Comment by enjoy-digital** [comment]
OK thanks for testing, i'll look at that.

**Comment by AnttiLukats** [comment]
e, I am using riscv-embed-none as toolchain prefix, but I bet this can not cause the uart printout to stop after 10 characters ?  weird..

**Comment by AnttiLukats** [comment]
when compiliny arty from litex-boards with "linux" variant the uart output is similar, maybe 12 characters come out from uart..

**Comment by enjoy-digital** [comment]
Can you test with the attached patch?
[0001-soc_core-use-same-mem_map-than-soc_linux.patch.txt](https://github.com/litex-hub/linux-on-litex-vexriscv/files/3467154/0001-soc_core-use-same-mem_map-than-soc_linux.patch.txt)

**Comment by AnttiLukats** [comment]
with this patch IT WORKS. hope it helps to find some guidance how to deal with this issue

**Comment by AnttiLukats** [comment]
update. it works on Artix FPGA's on Cyclone 10LP same result as before, no uart at all, there it may be different issue

**Comment by AnttiLukats** [comment]
working, C10LP RefKit booted to linux prompt.

**Comment by enjoy-digital** [comment]
Good, what was the issue?

**Comment by AnttiLukats** [comment]
missing "soc_reset" module
