### ISSUE TITLE
Some issues when I boot on tang-primer-20k

### ISSUE THREAD

**Issue by kevinsu20** [litex-hub/linux-on-litex-vexriscv#353]
Hi , i met some issues:
If i use this  project's codes , i can successfully build the bitstream.( include spi-sdcard and serial ) use the following command : `./make.py --board=tang_primer_20k`
but if I use Litex , i use the command `python3 sipeed_tang_primer_20k.py --cpu-type vexriscv_smp --with-spi-sdcard --build`
,the resources will not be enough.
![8bb61a95741bf83ffa4ce01eeb41ace](https://github.com/litex-hub/linux-on-litex-vexriscv/assets/142069108/8a6b50a0-c15f-4d77-8218-732f4936ce6c)
i ' m so confused of it . if you change cores or ips in this project?

**Comment by BobMa0420** [comment]
Hi, I uesd `./make.py --board=sipeed_tang_primer_20k --toolchain=Gowin --with-video-terminal --build` and got

> make.py: error: unrecognized arguments: --with-video-terminal

Do you have any idea of that? Thank you so much!

**Comment by enjoy-digital** [comment]
Hi @kevinsu20,

in the project, we are reducing the L2 size to avoid resources issue on this board, so you also had to reduce L2 size in your command line: 
`python3 -m litex_boards.targets.sipeed_tang_primer_20k --cpu-type vexriscv_smp --with-spi-sdcard --l2-size=512 --build `


@BobMa0420 : I don't think the FPGA will be large enough to enable both Linux and Video Terminal.
