### ISSUE TITLE
how to get the freq of the cpu

### ISSUE THREAD

**Issue by huangshaoxin** [litex-hub/linux-on-litex-vexriscv#370]
how can I get this cpu‘s freq to calculate the coremark score

**Comment by enjoy-digital** [comment]
Hi @huangshaoxin,

you could probably get it from the parsed .dts with something like:
`cat /proc/device-tree/cpus/cpu@0/clock-frequency`

Or install` util-linux` and/or `cpufrequtils` packages with buildroot to have access to `lscpu `and or `cpufreq-info`.
