### ISSUE TITLE
Boot Crash Afer  --============= Liftoff! ===============--

### ISSUE THREAD

**Issue by hex55** [litex-hub/linux-on-litex-vexriscv#382]
![image](https://github.com/litex-hub/linux-on-litex-vexriscv/assets/20609221/66756f4e-341d-4155-ad4e-f4041b746822)

![image](https://github.com/litex-hub/linux-on-litex-vexriscv/assets/20609221/790c47e5-cc91-40ff-b446-e01f735c9914)

Why the boot halt ? How to fix it ? I use an EG4S20NG256B board, it same to sipeed tang primer, but it maked by ICMaker.

**Comment by Dolu1990** [comment]
Hi,

The address used to load the binaries seems "not standard" related to the regular ones used in litex VexRiscv.
Did you updated the opensbi image ? (that would be the first step)

**Comment by hex55** [comment]
Thanks Dolu1990! Because the board only has 8MB SDRAM, the address was changed like that. I haven't modified the opensbi code yet, but I didn't see any information output by opensbi. It seems that I didn't enter opensbi.

**Comment by hex55** [comment]
> Hi,
> 
> The address used to load the binaries seems "not standard" related to the regular ones used in litex VexRiscv. Did you updated the opensbi image ? (that would be the first step)

Thanks Dolu1990! Because the board only has 8MB SDRAM, Jason's address was changed like that. I haven't modified the opensbi code yet, but I didn't see any information printed by opensbi. It seems that cpu didn't run opensbi. I will continue debugging tomorrow. Thank you for your help!

**Comment by Dolu1990** [comment]
So, first step is to focus on opensbi only i would say, until this boot, nothing else realy mathers :)
But 8MB of sdram, i don't think you can run linux on this ? I mean, especialy if the filesystem is in ram.

**Comment by hex55** [comment]
Hi 

> So, first step is to focus on opensbi only i would say, until this boot, nothing else realy mathers :) But 8MB of sdram, i don't think you can run linux on this ? I mean, especialy if the filesystem is in ram.

Hi Dolu1990, open sbi is work, next maybe as you save, I need put the rootfs in sd card. But I didn't find any information on this.
![Uploading image.png…]()

**Comment by hex55** [comment]
Hi 

> So, first step is to focus on opensbi only i would say, until this boot, nothing else realy mathers :) But 8MB of sdram, i don't think you can run linux on this ? I mean, especialy if the filesystem is in ram.

Hi Dolu1990, open sbi is work, next maybe as you save, I need put the rootfs in sd card. But I didn't find any information on this.

![Uploading 微信图片_20240514215045.png…]()

**Comment by hex55** [comment]
Hi 

> So, first step is to focus on opensbi only i would say, until this boot, nothing else realy mathers :) But 8MB of sdram, i don't think you can run linux on this ? I mean, especialy if the filesystem is in ram.

Hi Dolu1990, open sbi is work, next maybe as you save, I need put the rootfs in sd card. But I didn't find any information on this.
![1715694641506](https://github.com/litex-hub/linux-on-litex-vexriscv/assets/20609221/b6c4bf9f-805b-4857-9f6b-495a3301a607)

**Comment by hex55** [comment]
> So, first step is to focus on opensbi only i would say, until this boot, nothing else realy mathers :) But 8MB of sdram, i don't think you can run linux on this ? I mean, especialy if the filesystem is in ram.

![c0ea4d5e4b30a9389c2b88b33043f741](https://github.com/litex-hub/linux-on-litex-vexriscv/assets/20609221/e41c9b98-1c76-4a9b-b420-6bb4a999f747)

**Comment by Dolu1990** [comment]
between ramfs and sdcard, there is some changes : 
- remove the cpio from the  boot.json 
- In the dts, bootargs need to have root=/dev/mmcblk0p2 instead, and no more linux,initrd-start linux,initrd-end
- linux driver for the sdcard  (they may already be in)
- dts need also to have the entry for the sdcard, but litex will already generate them in the dts normaly

**Comment by hex55** [comment]
> between ramfs and sdcard, there is some changes :
> 
> * remove the cpio from the  boot.json
> * In the dts, bootargs need to have root=/dev/mmcblk0p2 instead, and no more linux,initrd-start linux,initrd-end
> * linux driver for the sdcard  (they may already be in)
> * dts need also to have the entry for the sdcard, but litex will already generate them in the dts normaly

Thanks for your guidance, I've got it done.
