### ISSUE TITLE
After booting to [10.122727] Waiting for root device /dev/mmcblk0p2... there is no response.

### ISSUE THREAD

**Issue by hex55** [litex-hub/linux-on-litex-vexriscv#383]
After booting to [10.122727] Waiting for root device /dev/mmcblk0p2... there is no response. The rootfs is in the SD card and is in ext4 format. Do you have any reference? Is there any reference material on booting from SD card? Thanks!
![image](https://github.com/litex-hub/linux-on-litex-vexriscv/assets/20609221/d2a07e43-2ae8-4c64-b590-453c692b7ce5)

**Comment by Dolu1990** [comment]
When you boot using the ramfs, can you get the sdcard to work in the linux terminal ? that would be the first easy step (if you can boot with the ramfs ?)

**Comment by Dolu1990** [comment]
(I do not have any self contained reference)

**Comment by hex55** [comment]
> When you boot using the ramfs, can you get the sdcard to work in the linux terminal ? that would be the first easy step (if you can boot with the ramfs ?)

Thank you, My rom cannot run rootfs because it is only 8M. This morning I successfully ran linux on the sdcard, yes, it can only be used as a toy.

**Comment by hex55** [comment]
> (I do not have any self contained reference)

ok. I still thank you!
