### ISSUE TITLE
Error with the Prebuilt images 

### ISSUE THREAD

**Issue by azaad-deepgrid** [litex-hub/linux-on-litex-vexriscv#385]
![Screenshot 2024-05-27 121208](https://github.com/litex-hub/linux-on-litex-vexriscv/assets/170522054/8146900e-037c-483a-be22-1c5add6f7864)
I have unzipped the folders from the https://github.com/litex-hub/linux-on-litex-vexriscv/issues/164 in the Images directory. Iam facing this issue. Can you please help me with this.

**Comment by Dolu1990** [comment]
Images need to be images (lowercase i)
