### ISSUE TITLE
SpinalHDL src code for Linux on LiteX implementation?

### ISSUE THREAD

**Issue by jjagielo** [litex-hub/linux-on-litex-vexriscv#401]
I want to understand the compiler and overall design a bit more for LiteX, and I am aware that many directories contain this submodule of [SpinalHDL](https://github.com/SpinalHDL/SpinalHDL/tree/002ffd50bca59e0f8b9c74b0d00cac86d8379810). Is there a specific _.scala_ file and related directories that point towards the implementation of Linux in SpinalHDL? Thanks!

**Comment by Dolu1990** [comment]
Hi,
Here is the main scala file used to generate the VexRiscv SMP SoC used in litex : 
https://github.com/SpinalHDL/VexRiscv/blob/master/src/main/scala/vexriscv/demo/smp/VexRiscvSmpLitexCluster.scala#L107

**Comment by jjagielo** [comment]
Thank you!
