### ISSUE TITLE
serial boot from BIOS on SoClinux stuck.

### ISSUE THREAD

**Issue by SeanGan233** [litex-hub/linux-on-litex-vexriscv#404]
hi everyone! i am testing demo on tang primer 20k board. Something confuses me.
when i use `python3 -m litex_boards.targets.sipeed_tang_primer_20k --build --load`(litex) to build, and `litex_term /dev/ttyUSB1 --kernel=demo.bin` to do serial boot , i can boot demo successfully.
but when i use `./make.py --board=sipeed_tang_primer_20k --cpu-count=1 --build --load`(linux-on-litex-vexriscv) to build, and `litex_term /dev/ttyUSB1 --kernel=demo.bin` to do serial boot, it stucks at `--============= Liftoff! ===============--`
Does the SoClinux have problems do serial boot? Can I do serial boot before booting linux?
any help appreciated.

**Comment by SeanGan233** [comment]
I print the memory space(main sram 0x40000000) after serial booting, and found that the value was exactly the same in both cases. Apparently the program has been written to the appropriate memory space, but somehow it does not boot from the space successfully.

**Comment by jeremy-heath** [comment]
I had this problem when I had a kernel larger than the memory region. Make sure that your kernel is not larger than the memory region (typically 8MB).
