### ISSUE TITLE
Print console messages as early as possible

### ISSUE THREAD

**Issue by enjoy-digital** [litex-hub/linux-on-litex-vexriscv#41]
With the switch to real LiteX UART driver (https://github.com/litex-hub/linux-on-litex-vexriscv/commit/4c138aef31a878be2d8454956cec3ef505191bc3 and https://github.com/litex-hub/linux-on-litex-vexriscv/commit/5e4d486f96feba490d461f27effb24d1adf2b1b0), first console messages seem to be buffered until the driver is loaded, so first console message can take up to a few seconds to appear on HW and up to a few minutes on Simulation. This is not convenient, especially for simulation and basic SoC verification (just see if Linux starts booting) since now take a few minutes instead of a few seconds.

**Comment by mithro** [comment]
FYI - @mateusz-holenko

**Comment by mithro** [comment]
@enjoy-digital - You might want to look at the `earlycon` kernel parameter?

Links
 * https://github.com/torvalds/linux/blob/master/drivers/tty/serial/earlycon.c
 * https://www.kernel.org/doc/html/v5.2/admin-guide/kernel-parameters.html
 * https://github.com/torvalds/linux/blob/146c3d3220e039b5d61bf810e0b42218eb020f39/Documentation/admin-guide/kernel-parameters.txt#L978
 * https://github.com/torvalds/linux/blob/04ce9318898b294001459b5d705795085a9eac64/drivers/tty/serial/Kconfig#L11-L16

**Comment by enjoy-digital** [comment]
Thanks @mithro,fixed by https://github.com/litex-hub/linux-on-litex-vexriscv/commit/2823bd9d3868d100f8f0cc70cf6e32decbf687fe.
