### ISSUE TITLE
run in NEXYS4DDR stalled, and Simulation stalled in boot Linux

### ISSUE THREAD

**Issue by dhm2013724** [litex-hub/linux-on-litex-vexriscv#48]
Hi everyone, I want to test this project in my Nexys4 DDR. I followed the README, there are no problems during make and install phase. But I met two problems in the last phase. 
First, the simulation stopped at booting Linux for too long times during sim.py. Should I still be waiting for it? 
![image](https://user-images.githubusercontent.com/15927157/65125748-8b2c6400-da28-11e9-9652-f11e45894995.png)
Second, when I tested it in Nexys4DDR, it stopped at [LXTERM] Starting....
![image](https://user-images.githubusercontent.com/15927157/65126008-16a5f500-da29-11e9-8ef7-dc41b840fdc2.png)
I have no idea, can anyone give me some advices? Thanks!

**Comment by dhm2013724** [comment]
After I modified two speed values(the speed in shell from 2e6 to 115200, the baudrate in sco_linux.py from 1e6 to 115200), some better things turned out.
![image](https://user-images.githubusercontent.com/15927157/65145419-21be4c80-da4c-11e9-8830-f74bbadeb87d.png)
But it still thrown out other errors....
![image](https://user-images.githubusercontent.com/15927157/65145620-90030f00-da4c-11e9-878e-cb19ad6c2ae1.png)

**Comment by dhm2013724** [comment]
I tried to re-build the bitstream, and now it shows like [issue#15](https://github.com/litex-hub/linux-on-litex-vexriscv/issues/15)
![image](https://user-images.githubusercontent.com/15927157/65150054-e0cb3580-da55-11e9-855b-1474771beff3.png)

**Comment by dhm2013724** [comment]
I also tried to boot from TFTP, but it returned the similar result.
![image](https://user-images.githubusercontent.com/15927157/65157641-9fda1d80-da63-11e9-8a70-7af9f9d8866f.png)

**Comment by mithro** [comment]
I believe @shenki just ran into the same issue?

**Comment by dhm2013724** [comment]
Now, the simulation and real hardware test stalled at the same point......Booting Linux.

**Comment by enjoy-digital** [comment]
This is now working correctly (i just re-tested it with updated prebuilt images). There was an issue in the .dtb generation that i introduced when testing the framebuffer with the NeTV2. That's now fixed.
