### ISSUE TITLE
Linux does not boot up 

### ISSUE THREAD

**Issue by scanakci** [litex-hub/linux-on-litex-vexriscv#50]
Running Sim.py n Ubuntu 18.04 machine does not boot up the Linux o. It stops at **Booting Linux** line:

        __   _ __      _  __
       / /  (_) /____ | |/_/
      / /__/ / __/ -_)>  <
     /____/_/\__/\__/_/|_|

 (c) Copyright 2012-2019 Enjoy-Digital
 (c) Copyright 2007-2015 M-Labs Ltd

 BIOS built on Sep 20 2019 18:48:03
 BIOS CRC passed (be166f00)

 Migen git sha1: 57a7311
 LiteX git sha1: 8b7d8217

--============ SoC info ================--
CPU:       VexRiscv @ 1MHz
ROM:       32KB
SRAM:      4KB
MAIN-RAM:  32768KB

--========= Peripherals init ===========--

--========== Boot sequence =============--
Booting from serial...
Press Q or ESC to abort boot completely.
sL5DdSMmkekro
Timeout
Executing booted program at 0x20000000
--============= Liftoff! ===============--
VexRiscv Machine Mode software built Sep 20 2019 18:48:01
--========== Booting Linux =============--

```

**Comment by enjoy-digital** [comment]
@scanakci sorry for the delay, have you tested with the prebuilt Linux images or with images you generated? (the prebuilt images should probably be updated).

**Comment by scanakci** [comment]
I tested the prebuild Linux images. When I use a commit from July, I could boot up. Probably, the prebuilt images should be updated as you said.

**Comment by enjoy-digital** [comment]
Ah ok thanks for the feedback, i'll update the bistreams/images soon.

**Comment by enjoy-digital** [comment]
The prebuilt images have been updated and simulation re-tested with it.
