### ISSUE TITLE
KC705: Lower uart_baudrate?

### ISSUE THREAD

**Issue by enjoy-digital** [litex-hub/linux-on-litex-vexriscv#91]
The KC705 uses a CP2103 for the UART which is limited to 921600. Check if 1e6 is working or if we need to lower baudrate for this board.

**Comment by atommann** [comment]
Baudrate of 1e6 does not work with my KC705, it always prints corrupted data.

**Comment by enjoy-digital** [comment]
Lowered to 500KBauds with https://github.com/litex-hub/linux-on-litex-vexriscv/commit/47ff12c8bfbdc5fe9e904a3ecf211419290c5885.
