### ISSUE TITLE
load fpga from remote server

### ISSUE THREAD

**Issue by winner96** [litex-hub/linux-on-litex-vexriscv#97]
Hi. I'm using Vivado at remote server, while my fpga is connected with jtag to host PC.

Maybe I can load fpga bitstream to host PC using Vivado GUI.

However, I don't know sure if 'lxterm --images=images.json /dev/ttyUSBX --speed=1e6 --no-crc' can load linux image to my host PC.

Is it possible to load from remote server to my host PC, not using TFTP? or other commands?

Thanks

**Comment by enjoy-digital** [comment]
@winner96: It's currently no possible to load the Linux images from JTAG. You need to use a serial link with the FPGA (and use lxterm) or Ethernet (and use TFTP). I hope it answers your questions. Please re-open if not.
